import { City, Vibe } from "./types";

export const CITIES: City[] = [
  { id: "ams", name: "Amsterdam", country: "Netherlands", slug: "amsterdam" },
  { id: "par", name: "Paris", country: "France", slug: "paris" },
  { id: "lon", name: "London", country: "United Kingdom", slug: "london" },
  { id: "ber", name: "Berlin", country: "Germany", slug: "berlin" },
  { id: "bcn", name: "Barcelona", country: "Spain", slug: "barcelona" },
];

export const VIBES: Vibe[] = [
  // Amsterdam
  {
    id: "ams-1",
    title: "Hortus Botanicus",
    description: "One of the oldest botanical gardens in the world. A quiet jungle in the city center.",
    imageUrl: "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800&q=80",
    category: "nature",
    cityId: "ams",
    tags: ["plants", "peaceful", "history", "green"],
    neighborhood: "Plantage",
    durationMinutes: 90,
    openingHour: 10,
    closingHour: 17,
    bestTimeOfDay: "morning",
    priceLevel: 2,
    lat: 52.3669,
    lng: 4.908,
  },
  {
    id: "ams-2",
    title: "NDSM Wharf",
    description:
      "A former shipyard turned into a brutalist art city. Street art, shipping containers, and industrial vibes.",
    imageUrl: "https://images.unsplash.com/photo-1641503070352-54f3ff29b253?q=80&w=1036",
    category: "culture",
    cityId: "ams",
    tags: ["industrial", "street art", "edgy", "ferry ride"],
    neighborhood: "Noord",
    durationMinutes: 120,
    bestTimeOfDay: "afternoon",
    priceLevel: 1,
    lat: 52.3992,
    lng: 4.8938,
  },
  {
    id: "ams-3",
    title: "De Pijp Street Markets",
    description: "The Albert Cuyp Market and surrounding cafes. The pulse of modern Amsterdam.",
    imageUrl: "https://res.cloudinary.com/autoura/image/upload/g_auto,c_fill,w_750,h_450/routes/xws4ijja6fhlzx7oupcs",
    category: "food",
    cityId: "ams",
    tags: ["food", "bustling", "local"],
    neighborhood: "De Pijp",
    durationMinutes: 60,
    openingHour: 9,
    closingHour: 17,
    bestTimeOfDay: "morning",
    priceLevel: 1,
    lat: 52.3561,
    lng: 4.8935,
  },
  {
    id: "ams-4",
    title: "Hidden Library (Rijksmuseum)",
    description: "The Cuypers Library is a 19th-century masterpiece often missed by the crowds.",
    imageUrl:
      "https://www.rijksmuseum.nl/assets/dfca0215-3725-4144-8a72-78bbba066011?w=1920&h=1080&fx=1856&fy=3167&c=a52362eb1593b509665338c55cad910b3fd434efb058b44b01e8461f7a0e30f4",
    category: "history",
    cityId: "ams",
    tags: ["books", "silence", "architecture", "dark academia"],
    neighborhood: "Museumkwartier",
    durationMinutes: 45,
    openingHour: 9,
    closingHour: 17,
    bestTimeOfDay: "afternoon",
    priceLevel: 3,
    lat: 52.36,
    lng: 4.8852,
  },
  {
    id: "ams-5",
    title: "Brown Cafe by the Canal",
    description: 'Classic Dutch "Bruin Café" for a quiet beer and bitterballen as the sun sets.',
    imageUrl: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800&q=80",
    category: "nightlife",
    cityId: "ams",
    tags: ["cozy", "beer", "local", "evening"],
    neighborhood: "Jordaan",
    durationMinutes: 90,
    openingHour: 16,
    closingHour: 23,
    bestTimeOfDay: "evening",
    priceLevel: 2,
    lat: 52.3752,
    lng: 4.8821,
  },

  // Paris
  {
    id: "par-1",
    title: "Palais Royal Gardens",
    description: "Symmetry and silence in the heart of Paris, framed by historic arcades.",
    imageUrl: "https://images.unsplash.com/photo-1471623320832-752e8bbf8413?w=800&q=80",
    category: "nature",
    cityId: "par",
    tags: ["classic", "quiet", "chic"],
    neighborhood: "1st Arr",
    durationMinutes: 60,
    bestTimeOfDay: "morning",
    priceLevel: 1,
    lat: 48.8642,
    lng: 2.3375,
  },
  {
    id: "par-2",
    title: "Le Marais Hidden Courtyards",
    description: "Exploring the medieval streets and finding secret gardens behind heavy doors.",
    imageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80",
    category: "history",
    cityId: "par",
    tags: ["medieval", "walking", "boutiques"],
    neighborhood: "Le Marais",
    durationMinutes: 120,
    bestTimeOfDay: "afternoon",
    priceLevel: 2,
    lat: 48.8575,
    lng: 2.3595,
  },
  // Add more as needed for other cities...
  // For MVS, we can stick to Amsterdam primarily or just populate a few for others.

  // London
  {
    id: "lon-1",
    title: "Barbican Conservatory",
    description: "A brutalist concrete jungle filled with tropical plants.",
    imageUrl: "https://images.unsplash.com/photo-1574515568448-f6217462bc2c?w=800&q=80",
    category: "architecture",
    cityId: "lon",
    tags: ["brutalist", "plants", "hidden"],
    neighborhood: "City of London",
    durationMinutes: 90,
    openingHour: 12, // often restricted
    closingHour: 19,
    bestTimeOfDay: "afternoon",
    priceLevel: 1,
    lat: 51.5194,
    lng: -0.0933,
  },

  // Berlin
  {
    id: "ber-1",
    title: "Tempelhofer Feld",
    description: "An abandoned airport turned into a massive public park. Cycle on the runway.",
    imageUrl: "https://images.unsplash.com/photo-1563228800-4b8cb670b377?w=800&q=80",
    category: "nature",
    cityId: "ber",
    tags: ["freedom", "cycling", "history", "vast"],
    neighborhood: "Tempelhof",
    durationMinutes: 120,
    bestTimeOfDay: "afternoon",
    priceLevel: 1,
    lat: 52.473,
    lng: 13.403,
  },

  // Barcelona
  {
    id: "bcn-1",
    title: "Bunkers del Carmel",
    description: "The best panoramic view of the city, away from the typical tourist spots.",
    imageUrl: "https://images.unsplash.com/photo-1560969184-10fe8719e654?w=800&q=80",
    category: "nature",
    cityId: "bcn",
    tags: ["view", "sunset", "history"],
    neighborhood: "Horta-Guinardó",
    durationMinutes: 90,
    bestTimeOfDay: "evening",
    priceLevel: 1,
    lat: 41.4194,
    lng: 2.1617,
  },
];
