import { describe, it, expect } from "vitest";
import { SchedulerEngine } from "../scheduler";
import { UserPreferences, EngineCandidate } from "../../types";

// Mock Data: Only 2 breakfast spots and 2 dinner spots for a 5-day trip
const mockPrefs: UserPreferences = {
  cityId: "sydney",
  startDate: "2026-01-23",
  endDate: "2026-01-27", // 5 days
  budget: "medium",
  likedVibes: [],
  dislikedVibes: [],
  vibeProfile: { weights: {}, swipes: 0 },
};

const mockCandidates: EngineCandidate[] = [
  {
    id: "b1",
    foursquareId: "fsq_b1",
    googlePlacesId: null,
    name: "Perfect Breakfast",
    cityId: "sydney",
    lat: -33.86,
    lng: 151.21,
    address: "123 Bakery St",
    rating: 8.5,
    website: null,
    phone: null,
    imageUrl: "https://example.com/b1.jpg",
    metadata: { categories: ["Bakery"], source: "fsq", website: null, phone: null },
    _score: 100,
  },
  {
    id: "d1",
    foursquareId: "fsq_d1",
    googlePlacesId: null,
    name: "Perfect Dinner",
    cityId: "sydney",
    lat: -33.87,
    lng: 151.22,
    address: "456 Steak St",
    rating: 9.0,
    website: null,
    phone: null,
    imageUrl: "https://example.com/d1.jpg",
    metadata: { categories: ["Steakhouse"], source: "fsq", website: null, phone: null },
    _score: 100,
  },
  // Some generic food places
  {
    id: "f1",
    foursquareId: "fsq_f1",
    googlePlacesId: null,
    name: "Generic Restaurant 1",
    cityId: "sydney",
    lat: -33.88,
    lng: 151.23,
    address: "789 Food Rd",
    rating: 7.5,
    website: null,
    phone: null,
    imageUrl: "https://example.com/f1.jpg",
    metadata: { categories: ["Thai Restaurant"], source: "fsq", website: null, phone: null },
    _score: 80,
  },
  {
    id: "f2",
    foursquareId: "fsq_f2",
    googlePlacesId: null,
    name: "Generic Restaurant 2",
    cityId: "sydney",
    lat: -33.89,
    lng: 151.24,
    address: "101 Food Rd",
    rating: 7.0,
    website: null,
    phone: null,
    imageUrl: "https://example.com/f2.jpg",
    metadata: { categories: ["Italian Restaurant"], source: "fsq", website: null, phone: null },
    _score: 75,
  },
  {
    id: "f3",
    foursquareId: "fsq_f3",
    googlePlacesId: null,
    name: "Generic Restaurant 3",
    cityId: "sydney",
    lat: -33.9,
    lng: 151.25,
    address: "202 Food Rd",
    rating: 6.5,
    website: null,
    phone: null,
    imageUrl: "https://example.com/f3.jpg",
    metadata: { categories: ["Diner"], source: "fsq", website: null, phone: null },
    _score: 70,
  },
  {
    id: "f4",
    foursquareId: "fsq_f4",
    googlePlacesId: null,
    name: "Generic Restaurant 4",
    cityId: "sydney",
    lat: -33.91,
    lng: 151.26,
    address: "303 Food Rd",
    rating: 6.0,
    website: null,
    phone: null,
    imageUrl: "https://example.com/f4.jpg",
    metadata: { categories: ["Bistro"], source: "fsq", website: null, phone: null },
    _score: 65,
  },
  {
    id: "f5",
    foursquareId: "fsq_f5",
    googlePlacesId: null,
    name: "Generic Restaurant 5",
    cityId: "sydney",
    lat: -33.92,
    lng: 151.27,
    address: "404 Food Rd",
    rating: 5.5,
    website: null,
    phone: null,
    imageUrl: "https://example.com/f5.jpg",
    metadata: { categories: ["Cafe"], source: "fsq", website: null, phone: null },
    _score: 60,
  },
  {
    id: "f6",
    foursquareId: "fsq_f6",
    googlePlacesId: null,
    name: "Generic Restaurant 6",
    cityId: "sydney",
    lat: -33.93,
    lng: 151.28,
    address: "505 Food Rd",
    rating: 5.0,
    website: null,
    phone: null,
    imageUrl: "https://example.com/f6.jpg",
    metadata: { categories: ["Sandwich Spot"], source: "fsq", website: null, phone: null },
    _score: 55,
  },
  {
    id: "f7",
    foursquareId: "fsq_f7",
    googlePlacesId: null,
    name: "Generic Restaurant 7",
    cityId: "sydney",
    lat: -33.94,
    lng: 151.29,
    address: "606 Food Rd",
    rating: 4.5,
    website: null,
    phone: null,
    imageUrl: "https://example.com/f7.jpg",
    metadata: { categories: ["Cafe"], source: "fsq", website: null, phone: null },
    _score: 50,
  },
  {
    id: "f8",
    foursquareId: "fsq_f8",
    googlePlacesId: null,
    name: "Generic Restaurant 8",
    cityId: "sydney",
    lat: -33.95,
    lng: 151.3,
    address: "707 Food Rd",
    rating: 4.0,
    website: null,
    phone: null,
    imageUrl: "https://example.com/f8.jpg",
    metadata: { categories: ["Bistro"], source: "fsq", website: null, phone: null },
    _score: 45,
  },
  {
    id: "f9",
    foursquareId: "fsq_f9",
    googlePlacesId: null,
    name: "Generic Restaurant 9",
    cityId: "sydney",
    lat: -33.96,
    lng: 151.31,
    address: "808 Food Rd",
    rating: 3.5,
    website: null,
    phone: null,
    imageUrl: "https://example.com/f9.jpg",
    metadata: { categories: ["Diner"], source: "fsq", website: null, phone: null },
    _score: 40,
  },
  {
    id: "f10",
    foursquareId: "fsq_f10",
    googlePlacesId: null,
    name: "Generic Restaurant 10",
    cityId: "sydney",
    lat: -33.97,
    lng: 151.32,
    address: "909 Food Rd",
    rating: 3.0,
    website: null,
    phone: null,
    imageUrl: "https://example.com/f10.jpg",
    metadata: { categories: ["Fast Food"], source: "fsq", website: null, phone: null },
    _score: 35,
  },
];

describe("Meal Exhaustion & Fallback", () => {
  it("should ensure every day has breakfast and dinner by using loose matches", async () => {
    const engine = new SchedulerEngine(mockPrefs);
    const itinerary = await engine.assembleItinerary(mockCandidates);

    expect(itinerary.days.length).toBe(5);

    for (const day of itinerary.days) {
      const breakfast = day.activities.find((a) => a.startTime === "08:00");
      const dinner = day.activities.find((a) => a.startTime === "19:30");

      expect(breakfast, `Day ${day.dayNumber} missing breakfast`).toBeDefined();
      expect(dinner, `Day ${day.dayNumber} missing dinner`).toBeDefined();

      console.log(`Day ${day.dayNumber}: Breakfast=${breakfast?.vibe.title}, Dinner=${dinner?.vibe.title}`);
    }
  });
});
